# Generated by Django 6.0 on 2025-12-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dosen', 'Dosen'), ('mahasiswa', 'Mahasiswa')], max_length=20),
        ),
    ]
