# Generated by Django 6.0 on 2025-12-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_submission_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='lastModified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
