# Generated by Django 6.0 on 2025-12-31 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_mahasiswa_name'),
        ('submissions', '0003_submission_lastmodified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.mahasiswa'),
        ),
    ]
