# Generated by Django 6.0 on 2026-01-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_submission_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='lastModified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
