# Generated by Django 6.0 on 2025-12-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
