# Generated by Django 6.0 on 2025-12-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
