# Generated by Django 6.0 on 2025-12-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='course',
            new_name='lesson',
        ),
    ]
