# Generated by Django 6.0 on 2025-12-29 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_linkmeet_course_linkwa_course_thumbnail_and_more'),
        ('lessons', '0002_lesson_description_alter_lesson_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
        ),
    ]
