# Generated by Django 6.0 on 2025-12-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='name',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
